name: GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'beta'
      - name: Setup and Build
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "brunch.tools" > build/web/CNAME
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
